#!/usr/bin/env python
#   Copyright 2016 Jamie Cressey
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import argparse
from apts3 import AptS3

parser = argparse.ArgumentParser()
parser.add_argument("action", help="[upload]",
                    type=str)
parser.add_argument("files", help="List of deb packages to process",
                    type=str)
parser.add_argument(
    "-a",
    "--arch",
    help="The architecture of the package in the APT repository.",
    type=str)
parser.add_argument(
    "-b",
    "--bucket",
    help="The name of the S3 bucket to upload to.",
    type=str)
parser.add_argument(
    "-c",
    "--codename",
    help="The codename of the APT repository.",
    type=str,
    default='stable')
parser.add_argument(
    "-l",
    "--lock",
    help="Lock the repo from other changes whilst running. Default: false",
    action="store_true")
parser.add_argument(
    "-m",
    "--component",
    help="The component of the APT repository. Default: main.",
    type=str,
    default="main")
parser.add_argument(
    "-p",
    "--preserve-versions",
    help="Whether to preserve other versions of a package in the repository when uploading one.",
    action="store_true")
parser.add_argument(
    "-r",
    "--prefix",
    help="The path prefix to use when storing on S3.",
    type=str)
parser.add_argument(
    "-s",
    "--sign",
    help="Sign the Release file. Use --sign with your key ID to use a specific key.",
    type=str)
parser.add_argument(
    "-t",
    "--lock_timeout",
    help="Timeout in seconds to wait for a lockfile to release. Default: 120",
    type=int,
    default=120)
parser.add_argument(
    "-v",
    "--visibility",
    help="The access policy for the uploaded files. Can be public, private, or authenticated. Default: public",
    type=str,
    default="public-read")
parser.add_argument(
    "--profile",
    help="The AWS profile to use for connecting to S3.",
    type=str)
parser.add_argument(
    "--region",
    help="The AWS region to use for connecting to S3.",
    type=str)
args = parser.parse_args()

AptS3(args)
